# Introduction to sklearn 

Useful functions :

0. An end to end Scikit-learn workflow
1. Getting the data ready
2. Choose the right estimator/algo for our problem
3. Fit the model/algo and use it to make predictions
4. Evaluating the model
5. Improve the model
6. Save and load a trained model
7. Puttting it all together

## 0. An end to end Scikit-learn workflow

In [1]:
import numpy as np

In [2]:
#Get the data ready
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
heart = pd.read_csv("data/heart-disease.csv")
heart

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
import warnings 
warnings.filterwarnings("ignore")

In [4]:
# Create X (features matrix)
X = heart.drop("target", axis=1)

#Create Y (labels)
y = heart["target"]

In [5]:
# 2. Choose the right model and hyperparamters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# we keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [6]:
# 3. Fit the model to the data 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
clf.fit(X_train, y_train);

In [8]:
# make a prediction
y_label =clf.predict(np.array([0, 2, 3, 4]))

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [9]:
y_preds = clf.predict(X_test)
y_preds

array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1], dtype=int64)

In [10]:
y_test

116    1
120    1
53     1
239    0
127    1
      ..
29     1
293    0
12     1
178    0
118    1
Name: target, Length: 61, dtype: int64

In [11]:
# 4 .Evaluate the model 
clf.score(X_train, y_train)

1.0

In [12]:
clf.score(X_test, y_test)

0.7540983606557377

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.77      0.69      0.73        29
           1       0.74      0.81      0.78        32

    accuracy                           0.75        61
   macro avg       0.76      0.75      0.75        61
weighted avg       0.76      0.75      0.75        61



In [14]:
confusion_matrix(y_test, y_preds)

array([[20,  9],
       [ 6, 26]], dtype=int64)

In [15]:
accuracy_score(y_test, y_preds)

0.7540983606557377

In [16]:
# 5 .Improve the model
# Try diff ammounts of estimator

np.random.seed(42)
for i in range (10, 100, 10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%")
    print(" ")

Trying model with 10 estimators...
Model accuracy on test set: 75.41%
 
Trying model with 20 estimators...
Model accuracy on test set: 77.05%
 
Trying model with 30 estimators...
Model accuracy on test set: 80.33%
 
Trying model with 40 estimators...
Model accuracy on test set: 77.05%
 
Trying model with 50 estimators...
Model accuracy on test set: 75.41%
 
Trying model with 60 estimators...
Model accuracy on test set: 78.69%
 
Trying model with 70 estimators...
Model accuracy on test set: 77.05%
 
Trying model with 80 estimators...
Model accuracy on test set: 75.41%
 
Trying model with 90 estimators...
Model accuracy on test set: 78.69%
 


In [17]:
# 6. Save the model and load it 
import pickle

pickle.dump(clf, open("randomForestModel_1.pk1", "wb"))

In [18]:
loadedModel = pickle.load(open("randomForestModel_1.pk1", "rb"))
loadedModel.score(X_test, y_test)

0.7868852459016393

## 1. Getting data ready

The main things to do:
 1. Split the data into features and labels (usually 'X' & 'y')
 2. Filling/Imputing missing values
 3. Convert non numerical values to numeric(encoding)

In [19]:
heart.head(3)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1

In [20]:
X = heart.drop("target", axis=1)
X.head(3)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2

In [21]:
y = heart["target"]
y.head(3)

0    1
1    1
2    1
Name: target, dtype: int64

In [22]:
# Split the data to training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [23]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

## Make it Numerical

In [24]:
carSales = pd.read_csv("data/car-sales-extended.csv")
carSales.head(3)

Make Colour  Odometer (KM)  Doors  Price
0  Honda  White          35431      4  15323
1    BMW   Blue         192714      5  19943
2  Honda  White          84714      4  28343

In [25]:
carSales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [26]:
#split the data 
X = carSales.drop("Price", axis=1 )
y = carSales["Price"]

# Split to training and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [27]:
from sklearn.ensemble import RandomForestRegressor

model =RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Toyota'

In [28]:
# turn the categories into  numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categoricalFeatures = ["Make", "Colour", "Doors"]
OneHot = OneHotEncoder()
tranformer = ColumnTransformer([("OneHot", 
                                OneHot, 
                                categoricalFeatures)],
                                remainder="passthrough")
tranformedX = tranformer.fit_transform(X)
tranformedX

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [29]:
pd.DataFrame(tranformedX)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [30]:
X.head(5)

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [31]:
dummy = pd.get_dummies(carSales[["Make", "Colour", "Doors"]])
dummy

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4     False        True        False        False         False   
1        5      True       False        False        False         False   
2        4     False        True        False        False         False   
3        4     False       False        False         True         False   
4        3     False       False         True        False         False   
..     ...       ...         ...          ...          ...           ...   
995      4     False       False        False         True          True   
996      3     False       False         True        False         False   
997      4     False       False         True        False         False   
998      4     False        True        False        False         False   
999      4     False       False        False         True         False   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0          False         False       False          True  
1           True         False       False         False  
2          False         False       False          True  
3          False         False       False          True  
4           True         False       False         False  
..           ...           ...         ...           ...  
995        False         False       False         False  
996        False         False       False          True  
997         True         False       False         False  
998        False         False       False          True  
999         True         False       False         False  

[1000 rows x 10 columns]

In [32]:
# lets refil the model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(tranformedX, y, test_size=0.2)
model.fit(X_train, y_train);

In [33]:
model.score(X_test, y_test)

0.3235867221569877

### Missing Values

1. Fill them with some values
2. Remove the sample with missing data together

In [34]:
carMiss = pd.read_csv("data/car-sales-extended-missing-data.csv")
carMiss.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [35]:
#create x and y
X = carMiss.drop("Price", axis=1)
y = carMiss["Price"]

In [36]:
# Lets convert our data to numbers
# turn the categories into  numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categoricalFeatures = ["Make", "Colour", "Doors"]
OneHot = OneHotEncoder()
tranformer = ColumnTransformer([("OneHot", 
                                OneHot, 
                                categoricalFeatures)],
                                remainder="passthrough")
tranformedX = tranformer.fit_transform(X)
tranformedX

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4000 stored elements and shape (1000, 16)>

In [37]:
carMiss

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

#### Fill missing data with pandas

In [38]:
carMiss["Doors"].value_counts()

Doors
4.0    811
5.0     75
3.0     64
Name: count, dtype: int64

In [39]:
# Fil the make column
carMiss["Make"].fillna("missing", inplace=True)
carMiss["Colour"].fillna("missing", inplace=True)

carMiss["Odometer (KM)"].fillna(carMiss["Odometer (KM)"].mean(), inplace=True)

carMiss["Doors"].fillna(4, inplace=True)

In [40]:
carMiss.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [41]:
#Remove rows with missing price values
carMiss.dropna(inplace=True)
carMiss.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [42]:
X = carMiss.drop("Price", axis=1)
y = carMiss["Price"]

In [43]:
# turn the categories into  numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categoricalFeatures = ["Make", "Colour", "Doors"]
OneHot = OneHotEncoder()
tranformer = ColumnTransformer([("OneHot", 
                                OneHot, 
                                categoricalFeatures)],
                                remainder="passthrough")
tranformedX = tranformer.fit_transform(carMiss)
tranformedX

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

### Option 2: Fill missing values with scikitLearn

In [44]:
carMiss = pd.read_csv("data/car-sales-extended-missing-data.csv")
carMiss.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [45]:
#Drop rows with no label
carMiss.dropna(subset=["Price"], inplace=True)
carMiss.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [46]:
X = carMiss.drop("Price", axis=1)
y = carMiss["Price"]

In [47]:
# Fill missing values with Scikitlearn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill missing values with missng and numerical value with mean
catImputer = SimpleImputer(strategy="constant", fill_value="missing")
doorImputer = SimpleImputer(strategy="constant", fill_value=4)
numImputer = SimpleImputer(strategy="mean")

#Define columns
catFeature = ["Make", "Colour"]
doorFeature = ["Doors"]
numFeature = ["Odometer (KM)"]

# Create and Imputer(sth that fills the missing dta)
imputer = ColumnTransformer([("catImputer", catImputer, catFeature),
                             ("doorImputer", doorImputer, doorFeature),
                             ("numImputer", numImputer, numFeature)])

# Transform the data
filledX = imputer.fit_transform(X)
filledX

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [48]:
carSalesFilled = pd.DataFrame(filledX, 
                              columns=["Make", "Colour", "Doors", "Odometer (KM)"])
carSalesFilled

Make Colour Doors Odometer (KM)
0      Honda  White   4.0       35431.0
1        BMW   Blue   5.0      192714.0
2      Honda  White   4.0       84714.0
3     Toyota  White   4.0      154365.0
4     Nissan   Blue   3.0      181577.0
..       ...    ...   ...           ...
945   Toyota  Black   4.0       35820.0
946  missing  White   3.0      155144.0
947   Nissan   Blue   4.0       66604.0
948    Honda  White   4.0      215883.0
949   Toyota   Blue   4.0      248360.0

[950 rows x 4 columns]

In [49]:
carSalesFilled.isna().sum(), carSalesFilled.dtypes

(Make             0
 Colour           0
 Doors            0
 Odometer (KM)    0
 dtype: int64,
 Make             object
 Colour           object
 Doors            object
 Odometer (KM)    object
 dtype: object)

In [50]:
# turn the categories into  numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categoricalFeatures = ["Make", "Colour", "Doors"]
OneHot = OneHotEncoder()
tranformer = ColumnTransformer([("OneHot", 
                                OneHot, 
                                categoricalFeatures)],
                                remainder="passthrough")
transformedX = tranformer.fit_transform(carSalesFilled)
transformedX

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3800 stored elements and shape (950, 15)>

In [51]:
print(pd.DataFrame(tranformedX).head())

    0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
1  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
4  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   

         14       15  
0   35431.0  15323.0  
1  192714.0  19943.0  
2   84714.0  28343.0  
3  154365.0  13434.0  
4  181577.0  14043.0  


In [52]:
# Now we have got our data as numbers and filled(no missing values)
# Let's fit model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformedX, y, test_size=0.2)
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.21990196728583944

In [53]:
len(carSalesFilled), len(carSales)

(950, 1000)

## Choosing the right Estimator/algorithm for ut ptoblem
Some things to note:
* Sklearn refers to machine learning models, algorithms as estimators
* Classification problem predicting a category (heart disease or not)
   * Sometimes you will see clf (short for classifier) used as a classification estimator
* Regression problem - predicting a number (selling price of a car)

### Picking a machine learning model for regression problem
lets use the Carlifornia Housing data sets

In [54]:
# Getting the California Housing datasets
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [55]:
housingDf = pd.DataFrame(housing["data"], columns=housing["feature_names"])
housingDf

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [56]:
housingDf["MedHouseVal"] = housing["target"]
housingDf

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [57]:
housingDf["target"] = housing["target"]
housingDf

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  target  
0        -122.23        4.526   4.526  
1        -122.22        3.585   3.585  
2        -122.24        3.521   3.521  
3        -122.25        3.413   3.413  
4        -122.25        3.422   3.422  
...          ...          ...     ...  
20635    -121.09        0.781   0.781  
20636    -121.21        0.771   0.771  
20637    -121.22        0.923   0.923  
20638    -121.32        0.847   0.847  
20639    -121.24        0.894   0.894  

[20640 rows x 10 columns]

In [58]:
housingDf = housingDf.drop("MedHouseVal", axis=1)

In [59]:
housingDf

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [60]:
# Import algorithm 
from sklearn.linear_model import Ridge

# set up random seed
np.random.seed(42)

# create the data
X = housingDf.drop("target", axis=1)
y = housingDf["target"]

#split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#Instantiate and fit the model (on the training set)
model = Ridge()
model.fit(X_train, y_train)

# Check the score of the model (on the test set)
model.score(X_test, y_test)

# Lasso = 0.2841671821008396
# ElasticNet = 0.41655189098028245
# SVR(kernel="linear") = -0.01648536010717372
# EnsembleRegressors = 0.9345833333333333
    # RandomForest = 0.8065734772187598
# SVR(kernel="rbf") = -0.01648536010717372

0.5758549611440125

## Picking Machine Learning Model for Classification

In [61]:
# Using SVM 
from sklearn import svm

# set up random seed
np.random.seed(42)

# create the data
X = housingDf.drop("target", axis=1)
y = housingDf["target"]

#split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#Instantiate and fit the model (on the training set)
model = svm.SVR(kernel="rbf")
model.fit(X_train, y_train)

# Check the score of the model (on the test set)
model.score(X_test, y_test)

-0.01648536010717372

In [62]:
# Using Ensemble Model (Combination of smaller models to try and make better prediction than just a single model )

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.datasets import make_hastie_10_2

# set up random seed
np.random.seed(42)

# create the data
# X = housingDf.drop("target", axis=1)
# y = housingDf["target"]

X, y = make_hastie_10_2(random_state=0)

#split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#Instantiate and fit the model (on the training set)
# model = svm.SVR()
model = HistGradientBoostingClassifier().fit(X_train, y_train)

# Check the score of the model (on the test set)
model.score(X_test, y_test)


0.9345833333333333

In [63]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = housingDf.drop("target", axis=1)
y = housingDf["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()

model.fit(X_train, y_train)

model.score(X_test, y_test)

0.8065734772187598

## Choosing an estimatore for Classification problem

In [65]:
HeartDisease = pd.read_csv("data/heart-disease.csv")
HeartDisease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

Tidbit:
     1. If you have structured data, use ensembles methods
     2. If you have unstructured data, use deep learning ot transfer learning 

After consulting the map it says import linear svc 

In [70]:
# Import Linear Svc
from sklearn.svm import LinearSVC

np.random.seed(42)

X = HeartDisease.drop("target", axis=1)
y = HeartDisease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instatiate LinearSVC
clf = LinearSVC()

clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8688524590163934

In [71]:
HeartDisease["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [75]:
# Import RandomForestClassifier estimatore class 
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = HeartDisease.drop("target", axis=1)
y = HeartDisease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instatiate RandomForestClassifier
clf = RandomForestClassifier()

clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8524590163934426

## 3. Fit the model/algo and use it to make predictions

### 3.1 Fitting model to the data

* `X` = features, features variables, data
* `y` = labels, targets, targets variables

In [78]:
# Import RandomForestClassifier estimatore class 
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = HeartDisease.drop("target", axis=1)
y = HeartDisease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instatiate RandomForestClassifier
clf = RandomForestClassifier()

# Fit the model to the data (training the machine learning model)
clf.fit(X_train, y_train)

# Evaluate the random forest classifier (use the patterns the model has learned)
clf.score(X_test, y_test)

0.8524590163934426

In [76]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [77]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [80]:
X_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

### 3.2 Make prediction using MLM

2 ways to make predictions:
 1. `predict()`
 2. `predict_proba()`

In [81]:
# Use a trained model to make predictions
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [82]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [83]:
# Compare predictions to ruth labels to evaluate the model

y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [84]:
clf.score(X_test, y_test)

0.8524590163934426

In [86]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

 Make predictions with `predict_praba()`



In [88]:
# predict_proba() returns probabilities of a classification method
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [89]:
# Lets predict on the same data 
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

`predict()` can also be used i regression models

In [91]:
housingDf.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [93]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)

X = housingDf.drop("target", axis=1)
y = housingDf["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()

model.fit(X_train, y_train)

y_preds = model.predict(X_test)
# model.score(X_test, y_test)

In [95]:
y_preds[:5]

array([0.49384  , 0.75494  , 4.9285964, 2.54316  , 2.33176  ])

In [97]:
np.array(y_test[:5])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   ])

In [100]:
# Compare the predictions to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error( y_test, y_preds)

0.32659871732073664